Add Members Section
zairza-cetb/bench-routes-web pull request #10
Opened 2019-12-05 19:53 UTC by tulsi-prasad

This PR is a **WIP (Work in Progress)**. I have coded the section by making a ```member.js``` react component, and used _sass_ for writing the ```main.css```. Still as of now, the code ain't running, I might need some help in linking the ```main.css``` file to the ```member.js``` component. Thanks in advance!

2019-12-05 19:57 UTC, tulsi-prasad commented
![Annotation 2019-12-06 012549](https://user-images.githubusercontent.com/52394293/70268951-6e9dfd80-17c7-11ea-918a-f2d563ff8b99.png)

This is how it is supposed to look after the style sheets are linked.

2019-12-18 07:11 UTC, aquibbaig commented on package-lock.json
> +        "fast-deep-equal": "^2.0.1",
Add this to .gitignore

2019-12-18 07:13 UTC, aquibbaig commented on package-lock.json
> +        "fast-deep-equal": "^2.0.1",
Same implies for `website/package-lock.json`

2019-12-18 07:13 UTC, aquibbaig commented on website/pages/en/member.js
> +export default Members;
Add trailing whitespaces to the end of the file

2019-12-18 07:14 UTC, aquibbaig commented on website/static/index.html
> +</html>
Add trailing whitespaces(One more line)

2019-12-18 07:14 UTC, aquibbaig commented on website/static/sass/abstracts/_mixins.scss
> +}
Here

2019-12-18 07:14 UTC, aquibbaig commented on website/static/sass/abstracts/_variables.scss
> +$color-secondary-text: #24292e;
Here

2019-12-18 07:14 UTC, aquibbaig commented on website/static/sass/base/_typography.scss
> +}
Trailing line

2019-12-18 07:14 UTC, aquibbaig commented on website/static/sass/base/_utilities.scss
> +}
Here

2019-12-18 07:14 UTC, aquibbaig commented on website/static/sass/pages/_home.scss
> +}
And this too

2019-12-18 07:15 UTC, aquibbaig commented on yarn.lock
> +
`git checkout` this file too

2019-12-18 07:21 UTC, aquibbaig requested changes
Please update the PR w.r.t. changes requested

2019-12-18 15:00 UTC, tulsi-prasad commented
## Work Did
* Added whitespace after files, in commit [2d10abi](https://github.com/zairza-cetb/bench-routes-web/pull/10/commits/2d10ab1318cf312d199aa483601da63ba49ad116).
* Fetched the upstream from repo

## Concerns
*  `npm run start` failing in local master, with the following error:
```
Hp@LAPTOP-4CF3PCHH MINGW64 ~/Desktop/work/bench-routes-web/website (master)
$ npm run start

> @ start C:\Users\Hp\Desktop\work\bench-routes-web\website
> docusaurus-start

LiveReload server started on port 35729
Failed to start Docusaurus server: SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (16:0)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `docusaurus-start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hp\AppData\Roaming\npm-cache\_logs\2019-12-18T14_52_21_336Z-debug.log
```

2019-12-20 10:34 UTC, tulsi-prasad commented
Will be updated in a new PR, Closing this due to local conflicts.

2019-12-20 10:34 UTC, closed without merging